version: "3.9"
services:
  nginx:
    build:
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    volumes:
      - /Users/k/data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - /Users/k/data:/var/www/html
    networks:
      - web
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
  mariadb:
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - /Users/k/data/mysql:/var/lib/mysql
    networks:
      - web
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    restart: always
networks:
  web:
    name: wp-wordpress
    driver: bridge
