version: "3.9"
services:
  nginx:
    build:
      dockerfile: ./requirements/bonus/nginx/Dockerfile
    container_name: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    depends_on:
      - wordpress
      - mariadb
    restart: always
  wordpress:
    build:
      dockerfile: ./requirements/bonus/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - web
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
      - redis
    restart: on-failure
  mariadb:
    build:
      dockerfile: ./requirements/bonus/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - web
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    restart: always
  cadvisor:
    build:
      dockerfile: ./requirements/bonus/cadvisor/Dockerfile
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - web
    ports:
      - "8080:8080"
    restart: always
  vsftpd:
    build:
      dockerfile: ./requirements/bonus/vsftpd/Dockerfile
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
    container_name: vsftpd
    volumes:
      - wordpress:/home/${FTP_USER}
    env_file:
      - ./.env
    networks:
      - web
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      - wordpress
    restart: always
  redis:
    build:
      dockerfile: ./requirements/bonus/redis/Dockerfile
    container_name: redis
    networks:
      - web
    ports:
      - "6379:6379"
    restart: always
networks:
  web:
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/${USER}/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/${USER}/data/mariadb"
