version: "3.9"
services:
  nginx:
    build:
      dockerfile: ./requirements/bonus/nginx/Dockerfile
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: always
  wordpress:
    build:
      dockerfile: ./requirements/bonus/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
      - database
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: on-failure
  mariadb:
    build:
      dockerfile: ./requirements/bonus/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - database
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    restart: always
  vsftpd:
    build:
      dockerfile: ./requirements/bonus/vsftpd/Dockerfile
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
    container_name: vsftpd
    volumes:
      - wordpress:/home/k
    env_file:
      - ./.env
    networks:
      - vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      - wordpress
    restart: always
networks:
  vsftpd:
  wordpress:
  database:
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/k/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/k/data/mariadb"
